In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("dataset_Facebook.csv", delimiter=";")

In [5]:
print(df)

     Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
0              139441   Photo         2          12             4          3
1              139441  Status         2          12             3         10
2              139441   Photo         3          12             3          3
3              139441   Photo         2          12             2         10
4              139441   Photo         2          12             2          3
..                ...     ...       ...         ...           ...        ...
495             85093   Photo         3           1             7          2
496             81370   Photo         2           1             5          8
497             81370   Photo         1           1             5          2
498             81370   Photo         3           1             4         11
499             81370   Photo         2           1             4          4

     Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0     0.0                       2752                             5091
1     0.0                      10460                            19057
2     0.0                       2413                             4373
3     1.0                      50128                            87991
4     0.0                       7244                            13594
..    ...                        ...                              ...
495   0.0                       4684                             7536
496   0.0                       3480                             6229
497   0.0                       3778                             7216
498   0.0                       4156                             7564
499   NaN                       4188                             7292

     Lifetime Engaged Users  Lifetime Post Consumers  \
0                       178                      109
1                      1457                     1361
2                       177                      113
3                      2211                      790
4                       671                      410
..                      ...                      ...
495                     733                      708
496                     537                      508
497                     625                      572
498                     626                      574
499                     564                      524

     Lifetime Post Consumptions  \
0                           159
1                          1674
2                           154
3                          1119
4                           580
..                          ...
495                         985
496                         687
497                         795
498                         832
499                         743

     Lifetime Post Impressions by people who have liked your Page  \
0                                                 3078
1                                                11710
2                                                 2812
3                                                61027
4                                                 6228
..                                                 ...
495                                               4750
496                                               3961
497                                               4742
498                                               4534
499                                               3861

     Lifetime Post reach by people who like your Page  \
0                                                1640
1                                                6112
2                                                1503
3                                               32048
4                                                3200
..                                                ...
495                                              2876
496                                              2104
497                                              2388
498                                              2452
499                                              2200

     Lifetime People who have liked your Page and engaged with your post  \
0                                                  119
1                                                 1108
2                                                  132
3                                                 1386
4                                                  396
..                                                 ...
495                                                392
496                                                301
497                                                363
498                                                370
499                                                316

     comment    like  share  Total Interactions
0          4    79.0   17.0                 100
1          5   130.0   29.0                 164
2          0    66.0   14.0                  80
3         58  1572.0  147.0                1777
4         19   325.0   49.0                 393
..       ...     ...    ...                 ...
495        5    53.0   26.0                  84
496        0    53.0   22.0                  75
497        4    93.0   18.0                 115
498        7    91.0   38.0                 136
499        0    91.0   28.0                 119

[500 rows x 19 columns]

In [6]:
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [7]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [8]:
df['Paid'].fillna(0,inplace=True)

In [11]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   0
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [12]:
df['like'].fillna(0,inplace=True)
df['share'].fillna(0,inplace=True)

In [13]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   0
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   0
share                                                                  0
Total Interactions                                                     0
dtype: int64

In [15]:
df.duplicated().sum()

0

In [16]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278000,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.590000,27.048000,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448462,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.172528,42.511742,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.000000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.250000,32.000000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [22]:
print("Columsn Names :")
df.columns

Columsn Names :

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

In [23]:
for columns in df.columns:
    print("Unique values of '{columns}' column is :", df[columns].unique())

Unique values of '{columns}' column is : [139441 138414 138458 138895 138353 138329 138185 137893 137177 137059
 137020 136736 136642 136393 136013 135713 135700 135617 135428 135195
 134879 133679 133594 133451 132817 132201 131956 131808 131728 131630
 131300 130791 129600 128032 127082 126424 126345 126141 125612 124940
 123047 121540 120050 119198 117764 116435 116091 115893 115368 113028
 111620 109670 107907 106928 104070 102112 100732  98195  96749  93684
  93577  93470  93363  93256  93149  93042  92935  92828  92721  92614
  92507  92400  92293  92186  92079  91972  91865  91758  91651  91544
  91437  91330  91223  91116  91009  86909  86491  85979  85093  81370]
Unique values of '{columns}' column is : ['Photo' 'Status' 'Link' 'Video']
Unique values of '{columns}' column is : [2 3 1]
Unique values of '{columns}' column is : [12 11 10  9  8  7  6  5  4  3  2  1]
Unique values of '{columns}' column is : [4 3 2 1 7 6 5]
Unique values of '{columns}' column is : [ 3 10  9  5 12 11  2  4  8 13  7  6  1 14 23 22 15 20 19 18 17 16]
Unique values of '{columns}' column is : [0. 1.]
Unique values of '{columns}' column is : [  2752  10460   2413  50128   7244  10472  11692  13720  11844   4694
  21744   3112   2847   2549  22784  10060   1722  53264   3930   1591
   2848   1384   3454   2723   8488   8284  19552   2478   9560  36208
   4940   1683   5280   3002   3766   4512   2690  19800  17576   3290
  13280  18480   7268   2645   4284   7968  16576   1925   3786   1536
   1728  25248   4894   2935   2425  16416   5812   2545   2257  27072
  10940  50912  28752  27216   2352   3416   2149  53456   2168   3102
  39344 100768   9056  11444  13544  37376   1228  22984   1445   3754
   8728   5990   4582   2938   6692   2566  21176   4012   1531  24720
   2219   4732   2225   2626   3090   1101   2819  12468  12776   1357
  68896   1711   1388  70144   3674   9504   2426  13872   1673   1261
   2428   2227   1592    813  32208    729    834    786    584  15816
    619    617    677   3366    747    645    754    910   3906    659
    652    861   3690   4664   1080   8896   4018  68992  13152  31136
  16776  50736   5324  18120   2291  10744   3616  39984   4010   6564
   8612   5568   1685   3756   2656   5086   2055   9384   3992   7512
  11096   1060   2790  13856  10748  41984   2522   4480   1543  21256
   4484   4398  13216  22304   6208   4518   3582   9124  14152   4260
  30624   2363   2232   4048   1804   2351   3100   2360  19648   2295
   3934  34512   5282   1809   1920   1954  33536   4204   3376   9236
  72864   3358   3254  50640   3734   2594  22120   7980   1659   1006
  12728  28880   1330  14424  14200   5746   2540   4324   8260  20168
   5046  15296   3414  95424  14824   3504   2822   2973  10824   4592
   3176  10956  10888   3594   3384   4096  19968   4892  17360  21872
 180480  44464   2881   3460   3406   2602   5848  26944   5292  15576
  54256   3726  31904  40336   4220   4666   4274  28208   3330   3528
  38576   2628   7232  10188   6408  53056  66976  76096   5458   3706
  18320   2316 139008   5854 109056   3212   3046  12044   9652  28112
   8628   2431  20560  20896   2402   1729   4320   2585   3322   3600
  11620   4248   2763   3558   8324   6952   2823  63840  11608  58304
   4762   6150   4644  22464   4452   3576   3028   4022  52736  47376
   3234   6768  11304   3418   3662  56672   3294   3110   3806   3776
  39040   4032  21248   4344   2718   3024  10152   4708   2772   2812
   6460  18056   5016   6444   4458  12540   4362  38960   3144   4336
  81856   5728   5490  23832  18552   4132   4910   4202   5976   5206
   6984   6000   3332   9232   5212  24264   4280   5594  11336   5582
  28352  17912  35360   9084   6880  12824   6596   7492  44288 105632
 128064   5994   6172   4986   6668   5298  35008   5402   9880   3334
   3130  20920   3884   4240   3544   3286  71360   3824   6360   3714
  46192  39568  70912   4552   4390   4770   2970  34192   5302   5560
   4406   5290   3696   6030  49632   9120   1874   4122   5080   4068
   3272    238   6400   6876    391  10844   5132   3772   2933   4094
    452  11420   5704   7192   9604 122944   5730   4898   4118   1845
  34480   5338   5312   4412  98816   7220  14320  27056  20528   6416
   5786   5878   9528   8500   3796  28128   7228  55520   5880  10040
 153536 158208   6484   4840  15880  15288   9356   7732   5240   7132
  21928   5754  37088  39600   5536   6056  11484   4938  66784   5526
   5040   5168   5034   4908   9700   4800   6184  45920   8412   5400
   4684   3480   3778   4156   4188]
Unique values of '{columns}' column is : [   5091   19057    4373   87991   13594   20849   19479   24137   22538
    8668   42334    5590    5133    4896   39941   19680    2981  111785
    7509    2825    5066    2467    6853    4888   15294   15104   34143
    4306   18264   61262    9390    2929    9578    5318    7149    7808
    4628   28663   33058    6085   24198   28438   13989    4270    8387
   13023   30612    3481    7329    3094    3155   40125    8899    5439
    4462   31950   10465    4846    4372   84885   27951  164528   47358
   81908    5234    6167    4120   93790    3891    5939  103050  220447
   16362   46054   30235   68610    2392   59040    2774    8533   17827
   11123    9193    5799   13092    5244   54779    7955    2838    6056
   37240    4545    9303    4239    4943    5744    2548    5230   24917
   21893    2453  104952    3174    2544    5472  111745    7221   19556
    4469   27468    3655    2158    4510    4070    2749    1568   57472
    1374    1570    1573    1029   30514    1096    1071    1285    1240
    6647    1443    1117    1510    1673    8239    1158    1331    1565
    7659    9463    2427   17202    8617  229733   25666   59964   39549
  140432   11040   44940    3960   20691    6887  112830    7444   12097
   20151   10282    2999    7094    4862    9493    3915   14948    7255
   13633   21080    2004    4879   37716   19724   68290    4583    8039
    2874   41906    7829    8105   24738   37159   10830    6518   17776
   38806    7989   56950    4223    4005    7217    2968    4028    5388
    4004   33643    3721    6330   76659    8730    3130    3124    3530
   64850    7191    6557   16054  205934    5682    5644  121234    6218
    4220    3772   54734   12978    2845    1594   21685   64746    2327
   26000   26728    9874    7241   14305   35904    9084   25269    6369
  252207   21863    5699    5058    5063   20573    6691    5278   19279
   19744    6316    6166    7200   35161    8499   33613   40413  319133
   66824    5188    6503    5656    4349    9068   43464    9321   27513
   82011    6372   50539   65309    7774    8360    7948   41650    5461
    5918   55398    4264   12735   16978   11881    6050   65260  111502
   94644    9098    6194   31448    3611  277100   11854  191324    4908
    4909   20327   16968   47721   14847    4180   24112   29062    4072
    3289    7127    4410    5969    5807   21564    7004    4388    5396
   14480   11469    4955  102620   15323   80871    8303   10217    8178
   29650    6295    7998    5525    4794   73584   70212    5113    5553
   11525   20647   18474    5659    6476  104966    5499    5405    6486
    6736   55633    7278   34095    8025    4698    5630   17099    8090
    4642    4954   11373   32576    8745    6181   11509    7753   19301
    7378   65149    5067    7705  124753   10164    9518   42313   25542
    7165    9209    7633   10441    8962   12066   10300    5797   16811
    9035   51899    7594   11859    9586   15350    9903   55202   34774
   45260   15194   11736   18929    9835   12414   60918  147918  251269
    9970   10417    8198   10701    8875   45508    8891   12695    5953
    5313   55696   26026    6406    7057    6156    6276  110172    6333
   11079    6385   80227   47128   94172    7253    7716    4649   42092
    8769    9301    6769    8132    5824    9579 1110282   14759    2474
    7073    8238    7333    6079     570    5900   11941   10885     746
   22468    9067    6971    5144    7469     726   23855   10510   12811
   16557  457509   10083    7960    7355    2670  191207    9940    9411
    8070  125026   21958  162816   33000   11459   10634   10508   16535
   14157    6737   42940   12627    9100  665792   10115   17029  497910
  453213   10832    7466   51571   31467   16779   14986   13264    8893
   12060   39641    9238   10966    7927   10325   20696    7910    9456
    8779    8367    8371    8030    7491   17442    7754    8703   10228
    5808   13960    9218    7536    6229    7216    7564    7292]
Unique values of '{columns}' column is : [  178  1457   177  2211   671  1191   481   537  1530   280  4258   208
   193   249   887  1264   163  1706   130   121   200    15   118   176
  1341  1521  2806   212   973  1141   385   192   368   268   298   423
   252   479  5352   306  2055   517  2087   134   355   206  3572    97
   338    84   108   726   237   260   459   343   165   230   421   417
   630   802   541   232   356   197  1576   211   360   588  2101  1006
   555  1150    17   438   217   658  2295   657   454   321   199   384
   330   550   374   845   287   607   310   316   391   324   318  2143
   785    37  2624   288   224   357  3216   452  1132   320  2664   311
   369   370   323  1810   303   399   263   273  2733   257   229   251
   236   474   226   195   207   868   214   424   204   210  1480   428
  1032  2543  6164   714  1462   528  1967   111  2105   477   806   813
   746   322   469   390   622   346   757   598   769  1843   266   435
   519   892  3370   455   572  4840   545   584  2675  1805   644   626
  1476   631  2080   393   544   371   518   436  1359   377   512  1666
   703   365  1954   498  1151   946   394  2240   529   347   376   979
   345   277   844  1062   363   304  1393   389   548   997  2827   473
   699   444   135   372   128   913   451   487  1016   536  2573  3872
  8072  1052   571   877   756  2417  1620   602   863  1407   685   729
   701   964   513  1355   758  1473   909   515  2003  2889  1007   895
  3742   722  1779  1043  2552   735  1400  1631   870   936  1418   170
   596   753   569   610   691  1160   724   564   621   840   552  1382
   985   884   842   750   768  1029   791   666   664   579   647  1635
  1557   702   759   581   560  2579   526   732   577  1684   684  1049
   692   566  1636   678   823   679   470   734   491   344   604  2298
   392   574  3000   676  1701  1005   625   562   689   565   780   463
   908   736  1599   624   905   739   583   708  2750   339   962   830
   838  1215  3984  1539   718   662   669   700   524   522  1933   705
   601   509   504  1784   715  1364   741  1374   471   484   494   642
   612  1653   951    25   466   523   538   143   282   131  1409   398
   144    24   186  1411   587  1061  1373   103   546     9  1591   589
   603   711 11452  2348  1850  2299  1876  1362  1237  1383  1095   949
  2283  1239  1053  4544  1291  1429  1713  2482  1166  1188  1573  1245
   448  1066   857  1004  1512  1179  2728  1117  1762    66  2969  1096
  1020   957   975   956   810   733]
Unique values of '{columns}' column is : [  109  1361   113   790   410  1073   265   232  1407   183  4100   127
   115   134   337  1209   123  1103    86    88   142    15   104   118
  1270  1462  2531   124   559  1068   306   171   237   185   260   284
   168   424  5202  1912   366  2079   316   158  3464    83   283    76
    65   467   181   182   213   411   204   131   173   304   335   513
   654   298   156   995   288   460  1735   847   418   458   808    17
   374   167   640  2235   361   243   108   280   228   319   189   564
   220   352   216   257   287   218  1966   539    37  1326   245   219
   315  2628   330  1032  2570   324   238   314   356  1490   392   271
  2654   254   223   246   345   192   205   201   863   194   206   388
  1426   975  2438  5934   440  1450   483   282  1877    90  1921   370
   602   727   545   295   408   309   509   452   447   614  1724   251
   360   450   498  2420   390   430   334  4754   446  2584   984   473
   482  1397   549   435  1956   348   405   422   365   695   437  1333
   530   359   331   333  1016   409  1130   759   323   344  1577   434
   322   906   398   321   268   461   991   351   286  1354   632   431
   953  3244   477  2781   342   575   591   297   126   289   119   783
   354   395   406   592  2448  3822  4010   930   503   512   444   570
   740   646  2327   963   574   770  1330   597   648   638   827   478
   890   700  1441   861   493  1412  1054  2495   933   884  3682   716
  1643   947  2457   720   872  2193  1381  1537   843   383   860  1038
   145   681   560   569   656  1138   671   523   568   834   779  1229
   705   715   725   676   683   934   730   658   618   548   616  1622
   724   672  1065   733   546   522  1334   488   712   529  1183   607
   918   626   528  1599   594   479   485   706   875   415   625   432
  1702   484  1637   587   555  1570   495   561   481   544   492   631
   642  1485   742   670   547   620  1242  2567   325   916   639   623
   526   713  1105  2254  1408   838   684   633   497   565  1367   542
  1732   627  1096   652  1106   453   455   566   586   433   474   659
  1480   937    25   505   507   726   130  1339   144    23   203   184
  1342   554  1037  1268    71     9  1156   556   582   678 11328  2300
  1819  2127  1800  1313  1218  1087  1288  1029   940  2190  1189   994
  3586  1264  1346  1633  2319  1115   923  1071  1401  1175   381  1002
   837   944  1479  1143  2288   496  1099  1078  1635    63  2833  1058
  1023    59   993  1271   938   911   901   655  1111   756   708   508
   572   524]
Unique values of '{columns}' column is : [  159  1674   154  1119   580  1389   364   305  1692   250  4540   145
   133   168   417  1425   148  1655   112   111   184    20   130   143
  1489  1711  3420   149   885  1728   501   221   345   247   431   226
   805  6547   402  2720   460 12074   170   513   223  4802   126   450
    99    95   863   264   401   433   539   301   167   327   487   591
   952  1268   540   258   641   219  1469   202   512   695  2331  1153
   717   667  1341    19   542   211  2085  2828   379   141   469   329
   477  1359   483   850   518   289   299   360  2418   303  2576   881
    55  1952   339   931   482  4782  1512   325  3395  1619    49   323
   430   414   387  2286   331   510   318   308  3289   292   265   297
   495   287   224   252  2632   239   249   644   251  1932   616  1345
  3179  9237   720  8308   861   463  2201   118  3932   534   957  1390
   867   424   613   445   757   412   652   688   951  2106   337   672
   719  4074   547   599  5906   629   669  2969  1618   678   729   597
  1797   836   622  3253   476   458   602   352   392   609   486   990
  1977   772   494   428   443  1678   596   631  1560  1158   523  2779
   794   529   440  1751   521   354   683  1971   383  3214  1063   676
  1211  5106   906  3627   525   882   966   497   415   153   423   577
  1370   530   561   723   909   721  6017  7327  6242  1571   730   731
   588   795  1097  1033  3098  1419   785  1106  2251   838  1014  1020
  1237   787  1328  1236  2136 14974   710  2089  1641  4596  1181  1173
  7854   862  2356 19779  4906   897  1147  3599  2801  2438  7980  1126
  2048   286   735  1021   781   852   913  2042   920   650   775  1388
  1229  1871   940  1034   969  1000  1408  1072   948   870   740   995
  2824  2051   937   930  1874  1082   770   677  1850   892   880  2123
   848  1438   872   663  2755   889   604  1197   583  1157   396   767
  3000   507   847  2718  1049  2838   713   869   833   878  1116   886
   552  1967  1005  3153   771  1165  1048   724   923  1990  6591  1897
   864  1274  1746  3391  2506  1254   788   943   874   768  1078   658
   842   701   633  3383   822  1028   645  1697  1267   569   632   544
   389   979   984   571   857   742  1448  2567  1290    31   727   934
   653   834  4550  8415   766 11064  1690    26  1420  8049  2895  3941
  9614    97   675     9  1926   715   926 18115  3311  2170  2737  2654
  1652  1526  1380  1834  1422  1192  3400  1612  1326  6624  1878  2022
  2493  3412  1441  1410  2110  1725   505  1336  1226  1837  1452  3183
   581  1461  1427  2741    70  3645  1399  1348    71  1243  2007  1278
  1140   763  1632  1003   985   687   832   743]
Unique values of '{columns}' column is : [   3078   11710    2812   61027    6228   16034   15432   19728   15220
    4309   37849    3887    3779    3631   34415   17272    1868   92512
    5009    2116    3561    2196    6282    2964    9684   10266   17748
    2612    9217   30131    5860    1585    4480    3039    5782    5183
    3052    5187   23135    4986   17627   12078   13544    2330    7283
    6734   24363    2307    6336    2903    2313   16132    4914    3901
    3017   21436    4976    3675    3188   35637   15066   54653   14091
   26869    4101    4530    3302   32646    2873    3537   39304   59658
    9562   13737   26622   22100    2392   12716    1924    6838   15418
    5057    3691    3668    7549    3834   13858    4625    1210    4509
   14475    3189    6201    2570    3047    3521    1284    3128   15850
   13272    2154   35707    2226    2161    4485   43671    3832   16018
    3120   20198    2598    1911    2888    3227    2551    1402   56149
    1390    1401     943   23584     951     935    1098    3180    1252
     989    1430    1503    7736    1041    1249    1351    6951    7196
    2195   13838    6677   17842   20547   35977   11860   46252    8627
    4401    3020   17502    4263   70249    4406    7682   16890    5696
    1794    4935    3273    6200    2970   11148    4428    5503   16095
    1705    3501   26832   13674   34802    3031    5014    2373   35455
    4208    4799   19599   22864    6866    4215    3857   13887   19409
    4578   32033    3332    3247    4046    2293    3112    3927    2757
   24034    3121    5010   54860    5123    2541    3295   50076    5161
    5700   14014  122474    4200    5069   92348    4831    3418    2205
   46700    9342    1604    1055   15779   40181    1475   25539   25610
    7407    3655    4972   12905   26881    7723   22103    4518   78287
   13498    4487    3681    3764   20030    3238    3993   18838   14425
    4319    4708    4911   26701    7389   23338   24667  108752   22904
    3840    4371    4446    3342    6651   20270    5867   19078   42128
    4760   24010   27771    4404    5936   18035    4606   17365    3086
    8855   14450    7243    5005   23679   40203   31096    5307    4700
   25584    2545  107502    5901   48765    3399    3559   17717   15917
   41207   11970    3963    5648   19738    3147    4569    3802    4111
    3351   20024    5063    3519    3708   13786    7431    3579   32470
    8419    2289    6086    6253    5651    9376    4343    7037    4229
    3574    5416   18580   22710    3476    3484    7048   14792    7326
    4491    4930   78678    4658    4605    4955    4846   32021   11280
    3601    4114   15382    4664    3353    3382    6279   26514    5904
    4249    7910    5493   16914    5681   57722    3586    5156   52477
    6890    6549   37816   15973    4908    5768    6173    7055    6461
    8188    7886    4347   12996    6258   48466    4632    8391    5732
   13876    6315   47899   21009    9105   11853    9389   15678    8242
    8452   22130   48575   84046    6896    7692    5685    7956    5640
    8149    6733    7072    4954    3821   43980   13546    4747    5026
    5011    4010   47977    4447    6661    4441   32842   22022   42338
    4440    4607    5040    3346   22907    6021    6600    4550    6032
    4166    6956 1107833   13246    1483    5827    6630    5914    5079
     567    4650   10987    9403     723   18310    9065    6932    3972

In [27]:
photo=df[df['Type'] == 'Photo']
status=df[df['Type'] == 'Status']
link=df[df['Type'] == 'Link']
video=df[df['Type'] == 'Video']

In [32]:
print('photo is:')
print(photo)

print('Status is:')
print(status)

photo is:
     Page total likes   Type  Category  Post Month  Post Weekday  Post Hour  \
0              139441  Photo         2          12             4          3
2              139441  Photo         3          12             3          3
3              139441  Photo         2          12             2         10
4              139441  Photo         2          12             2          3
6              139441  Photo         3          12             1          3
..                ...    ...       ...         ...           ...        ...
495             85093  Photo         3           1             7          2
496             81370  Photo         2           1             5          8
497             81370  Photo         1           1             5          2
498             81370  Photo         3           1             4         11
499             81370  Photo         2           1             4          4

     Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0     0.0                       2752                             5091
2     0.0                       2413                             4373
3     1.0                      50128                            87991
4     0.0                       7244                            13594
6     1.0                      11692                            19479
..    ...                        ...                              ...
495   0.0                       4684                             7536
496   0.0                       3480                             6229
497   0.0                       3778                             7216
498   0.0                       4156                             7564
499   0.0                       4188                             7292

     Lifetime Engaged Users  Lifetime Post Consumers  \
0                       178                      109
2                       177                      113
3                      2211                      790
4                       671                      410
6                       481                      265
..                      ...                      ...
495                     733                      708
496                     537                      508
497                     625                      572
498                     626                      574
499                     564                      524

     Lifetime Post Consumptions  \
0                           159
2                           154
3                          1119
4                           580
6                           364
..                          ...
495                         985
496                         687
497                         795
498                         832
499                         743

     Lifetime Post Impressions by people who have liked your Page  \
0                                                 3078
2                                                 2812
3                                                61027
4                                                 6228
6                                                15432
..                                                 ...
495                                               4750
496                                               3961
497                                               4742
498                                               4534
499                                               3861

     Lifetime Post reach by people who like your Page  \
0                                                1640
2                                                1503
3                                               32048
4                                                3200
6                                                9328
..                                                ...
495                                              2876
496                                              2104
497                                              2388
498                                              2452
499                                              2200

     Lifetime People who have liked your Page and engaged with your post  \
0                                                  119
2                                                  132
3                                                 1386
4                                                  396
6                                                  379
..                                                 ...
495                                                392
496                                                301
497                                                363
498                                                370
499                                                316

     comment    like  share  Total Interactions
0          4    79.0   17.0                 100
2          0    66.0   14.0                  80
3         58  1572.0  147.0                1777
4         19   325.0   49.0                 393
6          3   249.0   27.0                 279
..       ...     ...    ...                 ...
495        5    53.0   26.0                  84
496        0    53.0   22.0                  75
497        4    93.0   18.0                 115
498        7    91.0   38.0                 136
499        0    91.0   28.0                 119

[426 rows x 19 columns]
Status is:
     Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
1              139441  Status         2          12             3         10
5              139441  Status         2          12             1          9
8              139441  Status         2          12             7          3
10             139441  Status         2          12             5         10
15             138414  Status         2          12             3         10
18             138414  Status         3          12             2          3
24             138414  Status         2          12             6         10
25             138458  Status         2          12             6          3
26             138458  Status         2          12             5         11
38             138895  Status         2          12             7          9
40             138895  Status         2          12             6         11
46             138353  Status         1          12             3         11
72             137893  Status         3          11             4         11
80             137177  Status         2          11             7          3
84             137177  Status         3          11             5          2
98             137020  Status         2          10             5          3
107            136736  Status         2          10             1          4
109            136736  Status         2          10             7          3
121            136393  Status         2          10             7          9
138            136013  Status         2          10             5          3
141            136013  Status         3          10             3         10
142            136013  Status         2          10             3          2
148            135713  Status         2          10             7          4
163            135617  Status         2           9             6          4
172            135195  Status         2           9             1         10
175            135195  Status         2           9             6         10
180            134879  Status         2           9             4          4
202            132817  Status         2           8             3          2
217            131956  Status         2           8             2         12
222            131808  Status         2           8             7          4
223            131808  Status         2           8             6         10
225            131808  Status         2           7             5         14
232            131630  Status         2           7             2          6
235            131300  Status         2           7             7         10
242            130791  Status         2           7             4          6
253            129600  Status         2           7             5         12
267            128032  Status         2           7             5         10
275            126424  Status         2           7             3         13
282            126345  Status         2           6             7         11
285            126141  Status         2           6             6          4
334            119198  Status         2           5             1          2
352            116435  Status         1           5             4          3
362            116091  Status         2           5             5          7
371            113028  Status         2           4             6          3
416            104070  Status         1           3             3         15

     Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
1     0.0                      10460                            19057
5     0.0                      10472                            20849
8     0.0                      11844                            22538
10    0.0                      21744                            42334
15    0.0                      10060                            19680
18    0.0                       3930                             7509
24    0.0                       8488                            15294
25    0.0                       8284                            15104
26    0.0                      19552                            34143
38    0.0                      17576                            33058
40    0.0                      13280                            24198
46    0.0                      16576                            30612
72    0.0                       9056                            16362
80    0.0                       8728                            17827
84    0.0                       6692                            13092
98    1.0                      12468                            24917
107   0.0                       9504                            19556
109   0.0                      13872                            27468
121   0.0                      15816                            30514
138   0.0                       8896                            17202
141   0.0                      13152                            25666
142   1.0                      31136                            59964
148   0.0                      10744                            20691
163   0.0                      11096                            21080
172   0.0                      21256                            41906
175   1.0                      13216                            24738
180   1.0                       9124                            17776
202   1.0                       9236                            16054
217   0.0                      14424                            26000
222   0.0                       8260                            14305
223   1.0                      20168                            35904
225   0.0                      15296                            25269
232   1.0                      10824                            20573
235   0.0                      10956                            19279
242   0.0                      17360                            33613
253   1.0                      15576                            27513
267   0.0                      10188                            16978
275   0.0                      18320                            31448
282   0.0                      12044                            20327
285   0.0                       8628                            14847
334   0.0                      10152                            17099
352   1.0                      23832                            42313
362   0.0                       9232                            16811
371   1.0                      17912                            34774
416   0.0                       9120                            14759

     Lifetime Engaged Users  Lifetime Post Consumers  \
1                      1457                     1361
5                      1191                     1073
8                      1530                     1407
10                     4258                     4100
15                     1264                     1209
18                      130                       86
24                     1341                     1270
25                     1521                     1462
26                     2806                     2531
38                     5352                     5202
40                     2055                     1912
46                     3572                     3464
72                     1006                      847
80                     2295                     2235
84                      199                      108
98                     2143                     1966
107                    1132                     1032
109                    2664                     2570
121                    2733                     2654
138                    1480                     1426
141                    2543                     2438
142                    6164                     5934
148                    1967                     1877
163                    1843                     1724
172                    4840                     4754
175                    2675                     2584
180                    1476                     1397
202                    1151                     1130
217                     304                      286
222                     997                      953
223                    3370                     3244
225                    2827                     2781
232                     135                      126
235                     128                      119
242                    2573                     2448
253                    2417                     2327
267                    1473                     1441
275                    3742                     3682
282                    2240                     2193
285                     870                      843
334                    1636                     1599
352                    1701                     1570
362                     908                      861
371                    2750                     2567
416                     951                      937

     Lifetime Post Consumptions  \
1                          1674
5                          1389
8                          1692
10                         4540
15                         1425
18                          112
24                         1489
25                         1711
26                         3420
38                         6547
40                         2720
46                         4802
72                         1153
80                         2828
84                          141
98                         2576
107                        1512
109                        3395
121                        3289
138                        1932
141                        3179
142                        9237
148                        2201
163                        2106
172                        5906
175                        2969
180                        1797
202                        1560
217                         383
222                        1211
223                        5106
225                        3627
232                         153
235                         130
242                        6017
253                        3098
267                        2136
275                        7854
282                        3599
285                        1692
334                        2755
352                        2838
362                        1967
371                        6591
416                        1290

     Lifetime Post Impressions by people who have liked your Page  \
1                                                11710
5                                                16034
8                                                15220
10                                               37849
15                                               17272
18                                                5009
24                                                9684
25                                               10266
26                                               17748
38                                               23135
40                                               17627
46                                               24363
72                                                9562
80                                               15418
84                                                7549
98                                               15850
107                                              16018
109                                              20198
121                                              23584
138                                              13838
141                                              20547
142                                              35977
148                                              17502
163                                              16095
172                                              35455
175                                              19599
180                                              13887
202                                              14014
217                                              25539
222                                              12905
223                                              26881
225                                              22103
232                                              20030
235                                              18838
242                                              23338
253                                              19078
267                                              14450
275                                              25584
282                                              17717
285                                              11970
334                                              15382
352                                              37816
362                                              12996
371                                              21009
416                                              13246

     Lifetime Post reach by people who like your Page  \
1                                                6112
5                                                7852
8                                                7912
10                                              18952
15                                               8548
18                                               2410
24                                               5244
25                                               5372
26                                               9824
38                                              11792
40                                               9344
46                                              12888
72                                               5180
80                                               7344
84                                               3336
98                                               7636
107                                              7616
109                                             10432
121                                             11912
138                                              7020
141                                             10280
142                                             18048
148                                              8964

In [33]:
merged_subsets=pd.concat([photo,status])

In [34]:
print(merged_subsets)

     Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
0              139441   Photo         2          12             4          3
2              139441   Photo         3          12             3          3
3              139441   Photo         2          12             2         10
4              139441   Photo         2          12             2          3
6              139441   Photo         3          12             1          3
..                ...     ...       ...         ...           ...        ...
334            119198  Status         2           5             1          2
352            116435  Status         1           5             4          3
362            116091  Status         2           5             5          7
371            113028  Status         2           4             6          3
416            104070  Status         1           3             3         15

     Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0     0.0                       2752                             5091
2     0.0                       2413                             4373
3     1.0                      50128                            87991
4     0.0                       7244                            13594
6     1.0                      11692                            19479
..    ...                        ...                              ...
334   0.0                      10152                            17099
352   1.0                      23832                            42313
362   0.0                       9232                            16811
371   1.0                      17912                            34774
416   0.0                       9120                            14759

     Lifetime Engaged Users  Lifetime Post Consumers  \
0                       178                      109
2                       177                      113
3                      2211                      790
4                       671                      410
6                       481                      265
..                      ...                      ...
334                    1636                     1599
352                    1701                     1570
362                     908                      861
371                    2750                     2567
416                     951                      937

     Lifetime Post Consumptions  \
0                           159
2                           154
3                          1119
4                           580
6                           364
..                          ...
334                        2755
352                        2838
362                        1967
371                        6591
416                        1290

     Lifetime Post Impressions by people who have liked your Page  \
0                                                 3078
2                                                 2812
3                                                61027
4                                                 6228
6                                                15432
..                                                 ...
334                                              15382
352                                              37816
362                                              12996
371                                              21009
416                                              13246

     Lifetime Post reach by people who like your Page  \
0                                                1640
2                                                1503
3                                               32048
4                                                3200
6                                                9328
..                                                ...
334                                              8980
352                                             21352
362                                              7200
371                                             11408
416                                              8004

     Lifetime People who have liked your Page and engaged with your post  \
0                                                  119
2                                                  132
3                                                 1386
4                                                  396
6                                                  379
..                                                 ...
334                                               1613
352                                               1578
362                                                843
371                                               2256
416                                                924

     comment    like  share  Total Interactions
0          4    79.0   17.0                 100
2          0    66.0   14.0                  80
3         58  1572.0  147.0                1777
4         19   325.0   49.0                 393
6          3   249.0   27.0                 279
..       ...     ...    ...                 ...
334        2    55.0   10.0                  67
352        6   210.0   39.0                 255
362        1   129.0   36.0                 166
371       17   447.0  123.0                 587
416        3    25.0    6.0                  34

[471 rows x 19 columns]

In [36]:
sort=df.sort_values(by='Page total likes')

In [37]:
print(sort)

     Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
499             81370   Photo         2           1             4          4
496             81370   Photo         2           1             5          8
498             81370   Photo         3           1             4         11
497             81370   Photo         1           1             5          2
493             85093   Photo         3           1             1          2
..                ...     ...       ...         ...           ...        ...
10             139441  Status         2          12             5         10
11             139441   Photo         2          12             5         10
13             139441   Photo         2          12             5          3
7              139441   Photo         3          12             7          9
0              139441   Photo         2          12             4          3

     Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
499   0.0                       4188                             7292
496   0.0                       3480                             6229
498   0.0                       4156                             7564
497   0.0                       3778                             7216
493   0.0                       8412                            13960
..    ...                        ...                              ...
10    0.0                      21744                            42334
11    0.0                       3112                             5590
13    0.0                       2549                             4896
7     1.0                      13720                            24137
0     0.0                       2752                             5091

     Lifetime Engaged Users  Lifetime Post Consumers  \
499                     564                      524
496                     537                      508
498                     626                      574
497                     625                      572
493                    1179                     1111
..                      ...                      ...
10                     4258                     4100
11                      208                      127
13                      249                      134
7                       537                      232
0                       178                      109

     Lifetime Post Consumptions  \
499                         743
496                         687
498                         832
497                         795
493                        1632
..                          ...
10                         4540
11                          145
13                          168
7                           305
0                           159

     Lifetime Post Impressions by people who have liked your Page  \
499                                               3861
496                                               3961
498                                               4534
497                                               4742
493                                               8632
..                                                 ...
10                                               37849
11                                                3887
13                                                3631
7                                                19728
0                                                 3078

     Lifetime Post reach by people who like your Page  \
499                                              2200
496                                              2104
498                                              2452
497                                              2388
493                                              5348
..                                                ...
10                                              18952
11                                               2174
13                                               1917
7                                               11056
0                                                1640

     Lifetime People who have liked your Page and engaged with your post  \
499                                                316
496                                                301
498                                                370
497                                                363
493                                                699
..                                                 ...
10                                                3798
11                                                 165
13                                                 183
7                                                  422
0                                                  119

     comment   like  share  Total Interactions
499        0   91.0   28.0                 119
496        0   53.0   22.0                  75
498        7   91.0   38.0                 136
497        4   93.0   18.0                 115
493       17  185.0   55.0                 257
..       ...    ...    ...                 ...
10         0  233.0   19.0                 252
11         0   88.0   18.0                 106
13         5  137.0   10.0                 152
7          0  325.0   14.0                 339
0          4   79.0   17.0                 100

[500 rows x 19 columns]

In [38]:
trans=df.transpose()

In [39]:
print(trans)

                                                       0       1       2    \
Page total likes                                    139441  139441  139441
Type                                                 Photo  Status   Photo
Category                                                 2       2       3
Post Month                                              12      12      12
Post Weekday                                             4       3       3
Post Hour                                                3      10       3
Paid                                                   0.0     0.0     0.0
Lifetime Post Total Reach                             2752   10460    2413
Lifetime Post Total Impressions                       5091   19057    4373
Lifetime Engaged Users                                 178    1457     177
Lifetime Post Consumers                                109    1361     113
Lifetime Post Consumptions                             159    1674     154
Lifetime Post Impressions by people who have li...    3078   11710    2812
Lifetime Post reach by people who like your Page      1640    6112    1503
Lifetime People who have liked your Page and en...     119    1108     132
comment                                                  4       5       0
like                                                  79.0   130.0    66.0
share                                                 17.0    29.0    14.0
Total Interactions                                     100     164      80

                                                       3       4       5    \
Page total likes                                    139441  139441  139441
Type                                                 Photo   Photo  Status
Category                                                 2       2       2
Post Month                                              12      12      12
Post Weekday                                             2       2       1
Post Hour                                               10       3       9
Paid                                                   1.0     0.0     0.0
Lifetime Post Total Reach                            50128    7244   10472
Lifetime Post Total Impressions                      87991   13594   20849
Lifetime Engaged Users                                2211     671    1191
Lifetime Post Consumers                                790     410    1073
Lifetime Post Consumptions                            1119     580    1389
Lifetime Post Impressions by people who have li...   61027    6228   16034
Lifetime Post reach by people who like your Page     32048    3200    7852
Lifetime People who have liked your Page and en...    1386     396    1016
comment                                                 58      19       1
like                                                1572.0   325.0   152.0
share                                                147.0    49.0    33.0
Total Interactions                                    1777     393     186

                                                       6       7       8    \
Page total likes                                    139441  139441  139441
Type                                                 Photo   Photo  Status
Category                                                 3       3       2
Post Month                                              12      12      12
Post Weekday                                             1       7       7
Post Hour                                                3       9       3
Paid                                                   1.0     1.0     0.0
Lifetime Post Total Reach                            11692   13720   11844
Lifetime Post Total Impressions                      19479   24137   22538
Lifetime Engaged Users                                 481     537    1530
Lifetime Post Consumers                                265     232    1407
Lifetime Post Consumptions                             364     305    1692
Lifetime Post Impressions by people who have li...   15432   19728   15220
Lifetime Post reach by people who like your Page      9328   11056    7912
Lifetime People who have liked your Page and en...     379     422    1250
comment                                                  3       0       0
like                                                 249.0   325.0   161.0
share                                                 27.0    14.0    31.0
Total Interactions                                     279     339     192

                                                       9    ...    490    491  \
Page total likes                                    139441  ...  85979  85979
Type                                                 Photo  ...  Photo  Photo
Category                                                 3  ...      3      3
Post Month                                              12  ...      1      1
Post Weekday                                             6  ...      6      6
Post Hour                                               10  ...     11      3
Paid                                                   0.0  ...    0.0    1.0
Lifetime Post Total Reach                             4694  ...   5280   6184
Lifetime Post Total Impressions                       8668  ...   8703  10228
Lifetime Engaged Users                                 280  ...    951    956
Lifetime Post Consumers                                183  ...    911    901
Lifetime Post Consumptions                             250  ...   1237   1140
Lifetime Post Impressions by people who have li...    4309  ...   5757   6085
Lifetime Post reach by people who like your Page      2324  ...   3300   3502
Lifetime People who have liked your Page and en...     199  ...    431    437
comment                                                  3  ...      1      1
like                                                 113.0  ...   79.0  105.0
share                                                 26.0  ...   30.0   46.0
Total Interactions                                     142  ...    110    152

                                                      492    493    494  \
Page total likes                                    85979  85093  85093
Type                                                 Link  Photo  Photo
Category                                                1      3      3
Post Month                                              1      1      1
Post Weekday                                            5      1      7
Post Hour                                              11      2     10
Paid                                                  0.0    0.0    0.0
Lifetime Post Total Reach                           45920   8412   5400
Lifetime Post Total Impressions                      5808  13960   9218
Lifetime Engaged Users                                753   1179    810
Lifetime Post Consumers                               655   1111    756
Lifetime Post Consumptions                            763   1632   1003
Lifetime Post Impressions by people who have li...  15766   8632   5654
Lifetime Post reach by people who like your Page    10720   5348   3230
Lifetime People who have liked your Page and en...    220    699    422
comment                                                 0     17     10
like                                                128.0  185.0  125.0
share                                                 9.0   55.0   41.0
Total Interactions                                    137    257    176

                                                      495    496    497  \
Page total likes                                    85093  81370  81370
Type                                                Photo  Photo  Photo
Category                                                3      2      1
Post Month                                              1      1      1
Post Weekday                                            7      5      5
Post Hour                                               2      8      2
Paid                                                  0.0    0.0    0.0
Lifetime Post Total Reach                            4684   3480   3778
Lifetime Post Total Impressions                      7536   6229   7216
Lifetime Engaged Users                                733    537    625
Lifetime Post Consumers                               708    508    572
Lifetime Post Consumptions                            985    687    795
Lifetime Post Impressions by people who have li...   4750   3961   4742
Lifetime Post reach by people who like your Page     2876   2104   2388
Lifetime People who have liked your Page and en...    392    301    363
comment                                                 5      0      4
like                                                 53.0   53.0   93.0
share                                                26.0   22.0   18.0
Total Interactions                                     84     75    115

                                                      498    499
Page total likes                                    81370  81370
Type                                                Photo  Photo
Category                                                3      2
Post Month                                              1      1
Post Weekday                                            4      4
Post Hour                                              11      4
Paid                                                  0.0    0.0
Lifetime Post Total Reach                            4156   4188
Lifetime Post Total Impressions                      7564   7292
Lifetime Engaged Users                                626    564
Lifetime Post Consumers                               574    524
Lifetime Post Consumptions                            832    743
Lifetime Post Impressions by people who have li...   4534   3861
Lifetime Post reach by people who like your Page     2452   2200
Lifetime People who have liked your Page and en...    370    316
comment                                                 7      0
like                                                 91.0   91.0
share                                                38.0   28.0
Total Interactions                                    136    119

[19 rows x 500 columns]

In [40]:
# Melt the DataFrame to long format
melted_df = pd.melt(df, id_vars=['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday', 'Post Hour', 'Paid'])

In [41]:
print(melted_df)

      Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
0               139441   Photo         2          12             4          3
1               139441  Status         2          12             3         10
2               139441   Photo         3          12             3          3
3               139441   Photo         2          12             2         10
4               139441   Photo         2          12             2          3
...                ...     ...       ...         ...           ...        ...
5995             85093   Photo         3           1             7          2
5996             81370   Photo         2           1             5          8
5997             81370   Photo         1           1             5          2
5998             81370   Photo         3           1             4         11
5999             81370   Photo         2           1             4          4

      Paid                   variable    value
0      0.0  Lifetime Post Total Reach   2752.0
1      0.0  Lifetime Post Total Reach  10460.0
2      0.0  Lifetime Post Total Reach   2413.0
3      1.0  Lifetime Post Total Reach  50128.0
4      0.0  Lifetime Post Total Reach   7244.0
...    ...                        ...      ...
5995   0.0         Total Interactions     84.0
5996   0.0         Total Interactions     75.0
5997   0.0         Total Interactions    115.0
5998   0.0         Total Interactions    136.0
5999   0.0         Total Interactions    119.0

[6000 rows x 9 columns]

In [42]:
# Assuming you want to pivot the melted data back to wide format based on variable 'variable'
wide_df = melted_df.pivot_table(index=['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday', 'Post Hour', 'Paid'], columns='variable', values='value').reset_index()

In [43]:
print(wide_df)

variable  Page total likes    Type  Category  Post Month  Post Weekday  \
0                    81370   Photo         1           1             5
1                    81370   Photo         2           1             4
2                    81370   Photo         2           1             5
3                    81370   Photo         3           1             4
4                    85093   Photo         3           1             1
..                     ...     ...       ...         ...           ...
488                 139441   Photo         3          12             7
489                 139441  Status         2          12             1
490                 139441  Status         2          12             3
491                 139441  Status         2          12             5
492                 139441  Status         2          12             7

variable  Post Hour  Paid  Lifetime Engaged Users  \
0                 2   0.0                   625.0
1                 4   0.0                   564.0
2                 8   0.0                   537.0
3                11   0.0                   626.0
4                 2   0.0                  1179.0
..              ...   ...                     ...
488               9   1.0                   537.0
489               9   0.0                  1191.0
490              10   0.0                  1457.0
491              10   0.0                  4258.0
492               3   0.0                  1530.0

variable  Lifetime People who have liked your Page and engaged with your post  \
0                                                     363.0
1                                                     316.0
2                                                     301.0
3                                                     370.0
4                                                     699.0
..                                                      ...
488                                                   422.0
489                                                  1016.0
490                                                  1108.0
491                                                  3798.0
492                                                  1250.0

variable  Lifetime Post Consumers  Lifetime Post Consumptions  \
0                           572.0                       795.0
1                           524.0                       743.0
2                           508.0                       687.0
3                           574.0                       832.0
4                          1111.0                      1632.0
..                            ...                         ...
488                         232.0                       305.0
489                        1073.0                      1389.0
490                        1361.0                      1674.0
491                        4100.0                      4540.0
492                        1407.0                      1692.0

variable  Lifetime Post Impressions by people who have liked your Page  \
0                                                    4742.0
1                                                    3861.0
2                                                    3961.0
3                                                    4534.0
4                                                    8632.0
..                                                      ...
488                                                 19728.0
489                                                 16034.0
490                                                 11710.0
491                                                 37849.0
492                                                 15220.0

variable  Lifetime Post Total Impressions  Lifetime Post Total Reach  \
0                                  7216.0                     3778.0
1                                  7292.0                     4188.0
2                                  6229.0                     3480.0
3                                  7564.0                     4156.0
4                                 13960.0                     8412.0
..                                    ...                        ...
488                               24137.0                    13720.0
489                               20849.0                    10472.0
490                               19057.0                    10460.0
491                               42334.0                    21744.0
492                               22538.0                    11844.0

variable  Lifetime Post reach by people who like your Page  \
0                                                   2388.0
1                                                   2200.0
2                                                   2104.0
3                                                   2452.0
4                                                   5348.0
..                                                     ...
488                                                11056.0
489                                                 7852.0
490                                                 6112.0
491                                                18952.0
492                                                 7912.0

variable  Total Interactions  comment   like  share
0                      115.0      4.0   93.0   18.0
1                      119.0      0.0   91.0   28.0
2                       75.0      0.0   53.0   22.0
3                      136.0      7.0   91.0   38.0
4                      257.0     17.0  185.0   55.0
..                       ...      ...    ...    ...
488                    339.0      0.0  325.0   14.0
489                    186.0      1.0  152.0   33.0
490                    164.0      5.0  130.0   29.0
491                    252.0      0.0  233.0   19.0
492                    192.0      0.0  161.0   31.0

[493 rows x 19 columns]